### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Wildtick** [kkilobyte/ditch-cros#4]
![image](https://github.com/user-attachments/assets/8da7fb6d-adc6-4834-81cc-8694391cdd85)
wait can I still just use ultramarine normally if I don't have an ARM Chromebook?

**Comment by kkilobyte** [comment]
if you don't have an arm chromebook you can just install ultramarine like you would normally do

**Comment by kkilobyte** [comment]
all of my chromebooks are x86-64 and run ultramarine wonderfully
